version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10
commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: sudo npm install
      - save_npm
  build:
    parameters:
      env:
        type: enum
        enum: ["staging", "default"]
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Update submodule
          command: git submodule update --init
      - run:
          name: Install firebase-tools
          command: sudo npm install -g firebase-tools
      - run: 
          name: Build vuejs
          command: npm run build
      - run:
          name: Deploy Firebase Hosting
          command: |
              firebase use << parameters.env >>
              firebase deploy --token $FIREBASE_TOKEN

workflows:
  setup_and_build:
    jobs:
      - setup:
          filters:
            branches:
              only: 
                - staging
                - master
      - build:
          name: deploy_stg
          env: staging
          requires:
            - setup
          filters:
            branches:
              only: staging
      - build:
          name: deploy_prod
          env: default
          requires:
            - setup
          filters:
            branches:
              only: master
