version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8
jobs:
  build:
    parameters:
      env:
        type: enum
        enum: ["staging", "default"]
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo npm install
      - run:
          name: Install firebase-tools
          command: sudo npm install -g firebase-tools
      - run: 
          name: Build vuejs
          command: npm run build
      - run:
          name: Deploy Firebase Hosting
          command: |
              firebase use << parameters.env >>
              firebase deploy --only hosting --token $FIREBASE_TOKEN

workflows:
  setup_and_build:
    jobs:
      - build:
          name: deploy_stg
          env: staging
          filters:
            branches:
              only: staging
      - build:
          name: deploy_prod
          env: default
          filters:
            branches:
              only: master